### PR TITLE
implement uuid support, implement db conversion and optimize imports

### PR DESCRIPTION
**Pull request by SonarBeserk**

### CODE REVIEW

**Comment by BjoernAkAManf** [comment]
Could you also add the column latestUsername and update the name on each join? This would be more  convenient in regards of Webinterfaces. If you fix these suggestions i can accept that pr and release it on BukkitDev. (In Regards of #18)

Oh and increment Version in pom.xml to 3.4.8

**Comment by SonarBeserk** [comment]
caching names would not be hard to do nor would increasing the version, but the pr already covers what it was intended to cover.

**Comment by BjoernAkAManf** [comment]
Anyway. Thanks for the pr. Gonna release it tomorrow or so on bukkitDev.

**Comment by SonarBeserk** [comment]
Might be good to take a look up fixing update events before you do.

**Comment by BjoernAkAManf** [comment]
What update event do you mean? I did not see any errors or issue

**Comment by SonarBeserk** [comment]
Your update events. Ive not been able to actually confirm they work nor why they are optional. It seems like for the sake of keeping data they would default to enabled or be always on.

**Comment by BjoernAkAManf** [comment]
They are optional, because they have always been since i overtook the plugin. It's using some reflection and a diffrent approach to register listeners, than usuall, but they worked for me locally - no problem in that.

**Comment by SonarBeserk** [comment]
They never seemed reliable in my experience. The quit event was never really called and such which is why in my original fork i did things manually using the actual event instead. Why use reflection when you have the real classes and dynamically added update events are not supported?

**Comment by BjoernAkAManf** [comment]
It's cleaner. Working dry. The events itself should work, they have barely been touched.

**Comment by SonarBeserk** [comment]
Using reflection instead of the supported way of doing events is not my definition of cleaner. also might we continue this in the irc instead?

**Pull request merged**
